### ISSUE TITLE
Getting "incorrectly formatted" errors for swagger file that works with previous version

### ISSUE THREAD

**Issue by natevecc** [twilio/guardrail#187] opened 2019-02-15 23:18 UTC
Using `"sbt-guardrail" % "0.44.0"` in a project causes 
```
Spec file service.yml is incorrectly formatted.
```
Reverting to `"sbt-guardrail" % "0.43.0"` works without errors.

It would be helpful if I could know why the parser is failing so I could fix the swagger file if it's incorrect or report a more useful error message 😄. If you point me in the right direction on this I'd gladly work on a code fix!

**Comment by blast-hardcheese** [comment] 2019-02-17 21:01
@natevecc That's not great, sorry to hear that! There are a couple ways to proceed here:

#### Using a custom branch of guardrail to get debug output from swagger-parser

I've been trying a few different things to get swagger-parser to emit more helpful errors; to that end, it may be possible to use https://github.com/blast-hardcheese/guardrail/commit/37d1d1f0fa2a24e238d84965e187bba08d411aca from the CLI to run against your specification.

I've added slf4j-simple v1.7.25, with a default properties definition that dumps all `trace`-level output to `/tmp/swagger-parser.log`.

The configuration options in your `build.sbt` can be directly mapped to the CLI flags; if you've never used the CLI before, spin up an SBT console and type `cli --help`, then just port the args over directly (ie, `Client(...)` becomes `cli --client ...`). That'll let you iterate directly with the codebase without having to go through the process of publishing multiple JARs/sbt plugin releases locally.

#### Alternately, manually prune your specification file until you find what's wrong

A more manual way of figuring out what's wrong with your specification is available, if the output in `/tmp/swagger-parser.log` is unhelpful:

1) Remove all `paths`, only try to run the `guardrail` task with `definitions`
  a) If the error occurs with `definitions`, reduce the number of definitions you're running against until you find the one that fails
2) Keep all `definitions`, but reduce the number of `paths` that you're running against, until you find the one that fails.

#### Next steps, after you have a minimal example

Given this procedure, the issue may become apparent immediately. Some initial things to look at would be how the swagger-parser is initialized, as we're using their 2to3 bridge instead of writing our own.

If it is a problem with how we're parsing the output, however, providing a minimal reproducible case in `modules/sample/src/main/resources/issues/` would be extraordinarily helpful, as even just ensuring we can run against your example file would help prevent regressions.

**Comment by griffio** [comment] 2019-02-24 18:05
👽I have replicated the same issue in the latest release since the change to using the OpenAPIParser 3 support.

⚙️When using the sbt plugin server generator - Is it possible that existing swagger specs are not converted using ReadSwagger method? It only works with the CLI command.

Using the sbt plugin - If you are passing a swagger 2.0 spec it's not converted to version 3.x by the ReadSwagger https://github.com/twilio/guardrail/blob/3913d7df1155882221369712ebbd3262c9e5365a/modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala#L27

The example spec works simply by changing swagger: "2.0" -> openapi: "3.0.1" 
```
openapi: "3.0.1"
info:
  title: Foo
  version: 1.0.0
host: localhost:1234
schemes:
  - http
paths:
  /foo:
    get:
      operationId: getFoo
      x-scala-package: foo
      parameters:
        - in: body
          name: foo
          schema:
            $$ref: "#/definitions/Foo"
      responses:
        200:
          description: Success
          schema:
            $$ref: "#/definitions/Bar"
definitions:
  Foo:
    type: object
    properties:
      a:
        type: string
  Bar:
    type: object
    x-scala-package: com.example.test
    properties:
      a:
        type: string

**Comment by blast-hardcheese** [comment] 2019-02-24 19:12
@griffio Was just able to reproduce, tracking this down now

**Comment by blast-hardcheese** [comment] 2019-02-24 19:58
@griffio Can you check to see whether evaluating  `com.twilio.guardrail.sbt.Tasks.guardrailTask((guardrailTasks in Compile).eval, (_root_.sbt.Keys.managedSourceDirectories in Compile).eval.head)` in `consoleProject` runs successfully?

I'm having quite the challenge tracking down what's actually wrong. My current hunch is some sort of runtime-class-failure fallback.

My output:
```
brick:guardrail-hello-world (master) blast$ sbt
[info] [...]
sbt:guardrail-hello-world> consoleProject
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> com.twilio.guardrail.sbt.Tasks.guardrailTask((guardrailTasks in Compile).eval, (_root_.sbt.Keys.managedSourceDirectories in Compile).eval.head)
res0: Seq[java.io.File] = List(/Users/blast/Documents/guardrail-hello-world/target/scala-2.12/src_managed/main/foo/definitions/package.scala, /Users/blast/Documents/guardrail-hello-world/target/scala-2.12/src_managed/main/foo/Implicits.scala, /Users/blast/Documents/guardrail-hello-world/target/scala-2.12/src_managed/main/foo/AkkaHttpImplicits.scala)
```

**Comment by griffio** [comment] 2019-02-24 20:24
My output for swagger 2.0
```
Welcome to Scala 2.12.7 (OpenJDK 64-Bit Server VM, Java 11.0.1).

com.twilio.guardrail.sbt.Tasks.guardrailTask((guardrailTasks in Compile).eval, (_root_.sbt.Keys.managedSourceDirectories in Compile).eval.head)
res0: Seq[java.io.File] = List(/Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/definitions/Foo.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/definitions/Bar.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/definitions/package.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/foo/Routes.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/Implicits.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/AkkaHttpImplicits.scala)
```

My output for openapi 3.0.1
```
com.twilio.guardrail.sbt.Tasks.guardrailTask((guardrailTasks in Compile).eval, (_root_.sbt.Keys.managedSourceDirectories in Compile).eval.head)
res7: Seq[java.io.File] = List(/Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/definitions/package.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/foo/Routes.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/Implicits.scala, /Users/griffio/projects/guardrail-01/target/scala-2.12/src_managed/main/server/AkkaHttpImplicits.scala)
```

**Comment by blast-hardcheese** [comment] 2019-02-24 20:32
`Foo` and `Bar` are not generated because `definitions` has been moved into `components` in OpenAPI 3.x. See:
```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        a:
          type: string
    Bar:
      type: object
      x-scala-package: com.example.test
      properties:
        a:
          type: string
```

**Comment by blast-hardcheese** [comment] 2019-02-24 20:45
I've gotten a lot of mileage out of https://mermade.org.uk/openapi-converter for converting my specifications to 3.0, but from what I can tell (and you just confirmed) there's some oddity in sbt directly. Asking in the sbt gitter channel. Thanks for helping track this down!

**Comment by blast-hardcheese** [comment] 2019-03-07 18:19
This actually seems to be related to OSGi confusion, see
- https://github.com/swagger-api/swagger-parser/issues/800
- https://github.com/swagger-api/swagger-parser/issues/1003

**Comment by griffio** [comment] 2019-03-08 16:32
👺Yes - I can replicate and see the issue in sbt now.

The OpenAPI Parser uses `ServiceLoader.load(SwaggerParserExtension.class)` and this doesn't appear to work inside sbt due to the ClassLoader failing to locate any classes to perform the conversion.

For example - I found reference to it here https://github.com/meetup/sbt-openapi/blob/master/src/main/scala/com/meetup/sbtopenapi/Plugin.scala#L64

🧀 This contrived task below does work in an sbt build as I override the Context ClassLoader
```
lazy val openapi = taskKey[Unit]("Parse OpenApi spec")

openapi := {
  Thread.currentThread().setContextClassLoader(classOf[SwaggerParserExtension].getClassLoader)
  val path = new File("/Users/griffio/projects/guardrail-01/swagger.yaml").toPath
  val rs= ReadSwagger[String](path, { spec => spec.toString})
  ReadSwagger.readSwagger(rs) match {
    case Right(spec) => println(spec)
    case Left(error) => println(error.toString)
  }
``` 
🍑 I wonder if we can get away with a cheeky ContextClassLoader before calling ReadSwagger?

**Comment by blast-hardcheese** [comment] 2019-03-11 15:31
@griffio It's better than what I was preparing to do, hardcoding the OSGi call 😉

I'd think that overriding the `ContextClassLoader` in `sbt-guardrail`, then resetting it before returning control seems like a good thing to do. If you've got time to poke around at this, it would be much appreciated, otherwise I will likely be able to take a look later this week.

**Comment by griffio** [comment] 2019-03-22 14:11
@blast-hardcheese With the updated plugin the issue seems to be resolved now - 
Updated project to `addSbtPlugin("com.twilio" %% "sbt-guardrail" % "0.44.0.1")`

Thanks for updating 🖌🎨

**Comment by blast-hardcheese** [comment] 2019-03-22 15:59
@griffio Thanks for confirming, and thanks again for finding the fix!

@natevecc Closing this now, feel free to reopen if upgrading to 0.44.0.1+ didn't solve the issue for you

**Closed by blast-hardcheese** 2019-03-22 15:59 UTC
