### ISSUE TITLE
`additionalProperties` doesn't work properly with `$ref`

### ISSUE THREAD

**Issue by kelnos** [twilio/guardrail#263] opened 2019-04-29 22:20 UTC
Consider the following:
```
openapi: 3.0.1
info:
  title: Whatever
  version: 1.0.0
paths:
  /foo:
    post:
      operationId: getFoo
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: object
      required:
        - something
        - props
      properties:
        something:
          type: string
        props:
          type: object
          additionalProperties:
            type: integer
            format: int32
    FooProps:
      type: object
      additionalProperties:
        type: integer
        format: int32
    FooNested:
      type: object
      required:
        - something
        - props
      properties:
        something:
          type: string
        props:
          $ref: "#/components/schemas/FooProps"

```
`Foo` comes out correct:
```
case class Foo(something: String, props: Map[String, Int])
```
However, I would expect `FooNested` to look the same, but instead we get:
```
case class FooNested(something: String, props: io.circe.Json)
```
(And `FooProps` isn't emitted at all, as I guess we'd expect.)

**Comment by blast-hardcheese** [comment] 2019-05-04 00:06
@kelnos This is because we don't attempt to do anything with nested object literals, `additionalProperties` just got lumped in with that. It's been on my to-do list for a while, both that and identical object deduplication (#77)

**Comment by blast-hardcheese** [comment] 2019-05-04 00:07
realizing this is just `core`, the language stuff will just magically work once this is resolved.

**Comment by kelnos** [comment] 2019-05-04 01:20
So it turns out this actually does work.  Sometime between 0.47.0 and 0.49.0 it got fixed.  And if it wasn't for https://github.com/twilio/guardrail/pull/281 it would actually work.

**Comment by blast-hardcheese** [comment] 2019-05-04 01:21
Oh woah! Slam this spec into a regression test and add it to #281 and we can close it out then!

**Comment by kelnos** [comment] 2019-05-04 01:24
Ah yeah, looks like you fixed it: https://github.com/twilio/guardrail/commit/364a06c12fd8925100f825365d77dc27e7b491ae

**Closed** 2019-05-04 01:24 UTC
Labels: core, enhancement, help wanted

**Comment by kelnos** [comment] 2019-05-04 01:25
Yah, I'm working on a test now.
